%% Output

text_disp = {
    sprintf('Science Cameras');
    sprintf('\n\nMastcam-Z');
    sprintf('\n\n     Tech Specs');
    sprintf('\n     MAIN JOB:  To take high-definition video, panoramic color and 3D images of the Martian surface and features in the atmosphere with');
    sprintf('                a zoom lens to magnify distant targets\n\n');
    sprintf('     LOCATION:  Mounted on the rover mast at the eye level of a 6 ½-foot-tall person (2 meters tall). The cameras are separated by 9.5 inches');
    sprintf('                (24.2 centimeters) to provide stereo vision.\n\n');
    sprintf('     MASS:      Approximately 8.8 pounds (about 4 kilograms)\n\n');
    sprintf('     POWER:     Approximately 17.4 watts\n\n');
    sprintf('     VOLUME:    Camera head, per unit\n\n');
    sprintf('                   4.3 by 4.7 by 10.2 inches');
    sprintf('                   (11 by 12 by 26 centimeters)');
    sprintf('\n                Digital electronics assembly:\n\n');
    sprintf('                   8.6 by 4.7 by 1.9 inches');
    sprintf('                   (22 by 12 by 5 centimeters)');
    sprintf('\n                Calibration target:\n\n');
    sprintf('                   3.9 by 3.9 by 2.7 inches');
    sprintf('                   (10 by 10 by 7 centimeters)\n\n');
    sprintf('     DATA RETURN:      Approximately 148 megabits per sol, average\n\n');
    sprintf('     COLOR QUALITY:    Similar to that of a consumer digital camera (2-megapixel)\n\n');
    sprintf('     IMAGE SIZE:       1600 by 1200 pixels maximum\n\n');
    sprintf('     IMAGE RESOLUTION: Able to resolve between about 150 microns per pixel (0.15 millimeter or 0.0059 inch) to 7.4 millimeters (0.3 inches)');
    sprintf('               per pixel depending on distance');
    
    sprintf('\n\nSuperCam');
    sprintf('\n\n     Tech Specs');
    sprintf('\n     MAIN JOB:  To identify the chemical composition of rocks and soils, including their atomic and molecular makeup\n\n');
    sprintf('     LOCATION:  Mounted on the "head" of the rover''s long-necked mast\n\n');
    sprintf('     MASS:      Mast-mounted sensor head:\n\n');
    sprintf('                   12 pounds');
    sprintf('                   (5.6 kilograms)');
    sprintf('\n                Rover body-mounted electronics:\n\n');
    sprintf('                   10.6 pounds');
    sprintf('                   (4.8 kilograms)');
    sprintf('\n                Calibration target:\n\n');
    sprintf('                   0.5 pound');
    sprintf('                   (0.2 kilograms)');
    sprintf('     POWER:     17.9 watts\n\n');
    sprintf('     VOLUME:    Mast-mounted sensor head:\n\n');
    sprintf('                   approximately 15 by 9 by 8 inches');
    sprintf('                   (38 by 24 by 19 centimeters\n\n');
    sprintf('     CALIBRATION TARGET:  1.18 inches diameter');
    sprintf('                          (3 centimeters)\n\n');
    sprintf('     COLOR QUALITY:    Similar to that of a consumer digital camera (2-megapixel)\n\n');
    sprintf('     DATA RETURN:      15.5 megabits per experiment or about');
    sprintf('                       4.2 megabits per day\n\n');

    sprintf('\n\nPIXL');
    sprintf('\n\n     Tech Specs');
    sprintf('\n     MAIN JOB:  To measure the chemical makeup of rocks at a very fine scale\n\n');
    sprintf('     LOCATION:  Mounted on the turret at the end of the robotic arm\n\n');
    sprintf('     MASS:      Arm-mounted sensor head:\n\n');
    sprintf('                   Nearly 10 pounds (4.3 kilograms)');
    sprintf('\n                Body-mounted electronics:\n\n');
    sprintf('                   About 6 pounds (2.6 kilograms)');
    sprintf('\n                Calibration target:\n\n');
    sprintf('                   About 0.033 pounds (0.015 kilograms)');
    sprintf('     POWER:     About 25 watts\n\n');
    sprintf('     VOLUME:    Arm-mounted sensor head:\n\n');
    sprintf('                   approximately 8.5 by 10.5 by 9 inches');
    sprintf('                   (21.5 by 27 by 23 centimeters)\n\n');
    sprintf('     CALIBRATION TARGETS:  Diameter of each of four disks:\n\n');
    sprintf('                               1.9 inches (5 millimeters)');
    sprintf('\n                             Pedestal base:\n\n');
    sprintf('                               15.3 by 1.18 inches (39 by 30 millimeters)\n\n');
    sprintf('     DATA RETURN:  Approximately 16 megabits per experiment, or about 2 megabytes per day');
    
    sprintf('\n\nSHERLOC');
    sprintf('\n\n     Tech Specs');
    sprintf('\n     MAIN JOB:  Fine-scale detection of minerals, organic molecules and potential biosignatures\n\n');
    sprintf('     LOCATION:  Mounted on the turret at the end of the robotic arm\n\n');
    sprintf('     MASS:      Turret:\n\n');
    sprintf('                   6.86 pounds (3.11 kilograms)');
    sprintf('\n                Body:\n\n');
    sprintf('                   3.55 pounds (1.61 kilograms) body\n\n');
    sprintf('     POWER:      Turret:\n\n');
    sprintf('                   32.2 watts');
    sprintf('\n                Body:\n\n');
    sprintf('                   16.6 watts\n\n');
    sprintf('     VOLUME:    10.2 by 7.8 by 2.6 inches');
    sprintf('                (26.0 by 20.0 by 6.7 centimeters)\n\n');
    sprintf('     DATA RETURN:  79.7 Mbits (raw)');
    sprintf('     SPATIAL RESOLUTION:');
    sprintf('                     Context imager:\n');
    sprintf('                           30 micrometers');
    sprintf('\n                     Laser:\n');
    sprintf('                           50 micrometers');
    sprintf('     FIELD OF VIEW:  Imaging:\n');
    sprintf('                           0.9 to 0.5 inches (2.3 by 1.5 centimeters)');
    sprintf('\n                     Spectroscopy:\n');
    sprintf('                           7 by 7 millimeters (0.275 inch)');
    };

app.TextArea.Value = text_disp;